defaults: &defaults
  computadoras:
    precios: [
  		{ "name": "Marca", "field": "marca" },
  		{ "name": "Marca del procesador", "field": "marca_procesador" },
  		{ "name": "Modelo del procesador", "field": "modelo_procesador" },
  		{ "name": "Memoria RAM", "field": "memoria" },
  		{ "name": "Disco Rígido", "field": "disco" },
  		{ "name": "Display", "field": "pantalla" },
  		{ "name": "OS", "field": "os" },
  		{ "name": "Touch", "field": "touch" }
    ]

    pagina_producto: [
    	{ "name": "Procesador marca", "field": "marca_procesador" },
    	{ "name": "Procesador modelo", "field": "modelo_procesador" },
    	{ "name": "RAM", "field": "memoria" },
    	{ "name": "HDD", "field": "disco" },
    	{ "name": "Display", "field": "pantalla" },
    	{ "name": "Sist. Operativo", "field": "os" },
    	{ "name": "Touch", "field": "touch", "boolean": true }
    ]
    
    productos_similares: [
      "categoria",
      "marca_procesador",
      "modelo_procesador"
    ]

    pricebands: {
      "AR": [
        [ ~, 2000 ],
        [ 2000, 3000 ],
        [ 3000, 4000 ],
        [ 4000, 5000 ],
        [ 5000, 6000 ],
        [ 6000, 7000 ],
        [ 7000, 8000 ],
        [ 8000, ~ ]
      ],
      "CL": [
        [ ~, 150000 ],
        [ 150000, 200000 ],
        [ 200000, 250000 ],
        [ 250000, 300000 ],
        [ 300000, 350000 ],
        [ 350000, 400000 ],
        [ 400000, 450000 ],
        [ 450000, 500000 ],
        [ 500000, 550000 ],
        [ 550000, 600000 ],
        [ 650000, 700000 ],
        [ 700000, ~ ]
      ]
    }

development:
  host: "idashboard.local"
  <<: *defaults

test:
  <<: *defaults

production:
  host: "idashboard.la"
  <<: *defaults
