defaults: &defaults
  computadoras:
    precios: [ 
		{ "name": "Marca", "field": "marca" }, 
		{ "name": "Marca del procesador", "field": "marca_procesador" }, 
		{ "name": "Modelo del procesador", "field": "modelo_procesador" }, 
		{ "name": "Memoria RAM", "field": "memoria" }, 
		{ "name": "Disco Rígido", "field": "disco" }, 
		{ "name": "Display", "field": "pantalla" }, 
		{ "name": "OS", "field": "os" }, 
		{ "name": "Touch", "field": "touch" } 
    ]

development:
  <<: *defaults
	
test:
  <<: *defaults
	
production:
  <<: *defaults