defaults: &defaults
  # computadoras
  product_type_1:
    precios: [
  		{ "name": "Marca", "field": "marca" },
  		{ "name": "Marca del procesador", "field": "marca_procesador" },
  		{ "name": "Modelo del procesador", "field": "modelo_procesador" },
  		{ "name": "Memoria RAM", "field": "memoria" },
  		{ "name": "Disco Rígido", "field": "disco" },
  		{ "name": "Display", "field": "pantalla" },
  		{ "name": "OS", "field": "os" },
  		{ "name": "Touch", "field": "touch" }
    ]

    pagina_producto: [
    	{ "name": "Procesador marca", "field": "marca_procesador" },
    	{ "name": "Procesador modelo", "field": "modelo_procesador" },
    	{ "name": "RAM", "field": "memoria" },
    	{ "name": "HDD", "field": "disco" },
    	{ "name": "Display", "field": "pantalla" },
    	{ "name": "Sist. Operativo", "field": "os" },
    	{ "name": "Touch", "field": "touch", "boolean": true }
    ]
    
    productos_similares: [
      "categoria",
      "marca_procesador",
      "modelo_procesador"
    ]

    pricebands: {
      "AR": [
        [ ~, 2000 ],
        [ 2000, 3000 ],
        [ 3000, 4000 ],
        [ 4000, 5000 ],
        [ 5000, 6000 ],
        [ 6000, 7000 ],
        [ 7000, 8000 ],
        [ 8000, ~ ]
      ],
      "CL": [
        [ ~, 150000 ],
        [ 150000, 200000 ],
        [ 200000, 250000 ],
        [ 250000, 300000 ],
        [ 300000, 350000 ],
        [ 350000, 400000 ],
        [ 400000, 450000 ],
        [ 450000, 500000 ],
        [ 500000, 550000 ],
        [ 550000, 600000 ],
        [ 650000, 700000 ],
        [ 700000, ~ ]
      ]
    }

    url_imagen_producto: "http://computadoras.idashboard.com.ar/images/productos"
    url_imagen_item: "http://computadoras.idashboard.com.ar/images/items"

    url_imagen_promo: {
      "Argentina": "http://computadoras.idashboard.com.ar",
      "Chile": "http://chile.computadoras.idashboard.com.ar"
    }

    productizador: {
      "propiedades": [
        "Categoría",
        "Marca",
        "Modelo",
        "Marca de Procesador",
        "Modelo de Procesador",
        "Familia de Procesador",
        "RAM",
        "HDD",
        "Pantalla",
        "CD/DVD",
        "OS",
        "Touch"
      ]
    }

    cargapromos: {
      "propiedades": [
        "Categoría",
        "Marca",
        "Modelo",
        "Marca de Procesador",
        "Modelo de Procesador",
        "Familia de Procesador",
        "RAM",
        "HDD",
        "Pantalla",
        "CD/DVD",
        "OS",
        "Touch"
      ]
    }

  # televisores
  product_type_2:
    precios: [
      { "name": "Marca", "field": "marca" }
    ]

    pagina_producto: [
      { "name": "Tamaño de pantalla", "field": "pantalla_size" },
      { "name": "Tipo de pantalla", "field": "categoria" }
    ]
    
    productos_similares: [
      "categoria",
      "pantalla_size"
    ]

    pricebands: {
      "AR": [
        [ ~, 2000 ],
        [ 2000, 3000 ],
        [ 3000, 4000 ],
        [ 4000, 5000 ],
        [ 5000, 6000 ],
        [ 6000, 7000 ],
        [ 7000, 8000 ],
        [ 8000, ~ ]
      ],
      "CL": [
        [ ~, 150000 ],
        [ 150000, 200000 ],
        [ 200000, 250000 ],
        [ 250000, 300000 ],
        [ 300000, 350000 ],
        [ 350000, 400000 ],
        [ 400000, 450000 ],
        [ 450000, 500000 ],
        [ 500000, 550000 ],
        [ 550000, 600000 ],
        [ 650000, 700000 ],
        [ 700000, ~ ]
      ]
    }

    url_imagen_producto: "http://televisores.idashboard.com.ar/images/productos"
    url_imagen_item: "http://televisores.idashboard.com.ar/images/items"

development:
  host: "idashboard.local"
  aws_bucket: "idashboard_dev"
  <<: *defaults

test:
  <<: *defaults

production:
  host: "idashboard.la"
  aws_bucket: "idashboard_heroku"
  <<: *defaults
