embed_assets: on # (on, off, datauri)
package_assets: always # (on, off, always)
javascript_compressor: uglifier

javascripts:
  basico:
    - public/javascripts/prototip.js
    - public/javascripts/lightbox.js
    - public/javascripts/idashboard.js
    - public/javascripts/rails.js

  pagina_producto:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/highcharts_graficar.js
    - public/javascripts/jquery-ui-1.8.14.custom.min.js
    - public/javascripts/jquery-ui-datepicker-es.js

  publicaciones:
    - public/javascripts/highcharts.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/tooltipsy.min.js
    - public/javascripts/selectores_encadenados.js

  graficos_sin_selectores_encadenados:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/tooltipsy.min.js
    - public/javascripts/highcharts_graficar.js

  graficos:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/tooltipsy.min.js
    - public/javascripts/highcharts_graficar.js
    - public/javascripts/selectores_encadenados.js

  jquery_ui:
    - public/javascripts/jquery-ui-1.8.14.custom.min.js
    - public/javascripts/jquery-ui-datepicker-es.js

  mis_reportes:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/highcharts_graficar.js

stylesheets:
  basico:
    - public/stylesheets/estilos.css
    - public/stylesheets/modalbox.css
    - public/stylesheets/prototip.css
    - public/stylesheets/lightbox.css
    - public/stylesheets/chosen.css
    - public/stylesheets/jquery-ui-1.8.14.custom.css
    - public/stylesheets/jquery-datepicker.css