embed_assets: datauri # (on, off, datauri)
package_assets: on # (on, off, always)
javascript_compressor: uglifier
s3_bucket: idashboard_assets
s3_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
s3_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
s3_upload_files:
  - public/stylesheets/*
  - public/javascripts/*

javascripts:
  jquery:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_stringify.js

  prototype_scriptaculous:
    - public/javascripts/prototype.js
    - public/javascripts/scriptaculous.js

  basico:
    - public/javascripts/prototip.js
    - public/javascripts/lightbox.js
    - public/javascripts/idashboard.js
    - public/javascripts/rails.js

  chosen:
    - public/javascripts/chosen.jquery.js

  pagina_producto:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/highcharts_graficar.js
    - public/javascripts/modalbox.js
    - public/javascripts/jquery-ui-1.8.14.custom.min.js
    - public/javascripts/jquery-ui-datepicker-es.js
    - public/javascripts/s3_upload.js

  publicaciones:
    - public/javascripts/highcharts.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/tooltipsy.min.js
    - public/javascripts/selectores_encadenados.js
    - public/javascripts/modalbox.js

  graficos_sin_selectores_encadenados:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/tooltipsy.min.js
    - public/javascripts/highcharts_graficar.js

  graficos:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/tooltipsy.min.js
    - public/javascripts/highcharts_graficar.js
    - public/javascripts/selectores_encadenados.js
    - public/javascripts/modalbox.js

  jquery_ui:
    - public/javascripts/jquery-ui-1.8.14.custom.min.js
    - public/javascripts/jquery-ui-datepicker-es.js

  flip:
    - public/javascripts/jquery-ui-1.8.18.custom.min.js
    - public/javascripts/jquery.flip.js

  mis_reportes:
    - public/javascripts/highcharts.js
    - public/javascripts/modules/exporting.js
    - public/javascripts/highcharts_graficar.js
    - public/javascripts/modalbox.js

  s3upload:
    - public/javascripts/s3_upload.js

  ejs:
    - public/javascripts/ejs_production.js

stylesheets:
  basico:
    - public/stylesheets/estilos.css
    - public/stylesheets/modalbox.css
    - public/stylesheets/prototip.css
    - public/stylesheets/lightbox.css
    - public/stylesheets/chosen.css
    - public/stylesheets/jquery-ui-1.8.14.custom.css
    - public/stylesheets/jquery-datepicker.css
  chosen_productizador:
    - public/stylesheets/chosen-productizador.css
  grid_cargapromos:
    - public/stylesheets/grid_cargapromos.css
