development:
  host: localhost
  database: gardens_development

test:
  host: localhost
  database: gardens_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>